### ISSUE TITLE
API ideas

### ISSUE THREAD

**Issue by tbtommyb** [GlobeTownDevs/api#1]
Hey, so given that this is only a two day thing that's not going to be really used I'd like to make something that combines a couple of APIs in a slightly pointless way.

I was thinking of something that takes e.g. Guardian/BBC headlines as an input and passing it through [this](https://www.textrazor.com/) to extract the key words as use them as an input for a Youtube search or something, so generating a video associated with each headline.

Or taking a random entry from Wikipedia and using it to search Flickr etc.

**Comment by lucymonie** [comment]
I was just trawling through some api sites, and I was wondering whether we could take the weather (weather api) for a location (geo locations api) and translate it into pirate speak using [this api](http://isithackday.com/arrpi.php). So we could end up with things [like this](http://isithackday.com/arrpi.php?text=the%20weather%20in%20London%20today%20is%20stormy). It's kind of silly but it could be fun. The mvp could just be a weather app and the pirate speak thing with the geo points if we have time.

**Comment by njsfield** [comment]
Awesome idea! I love the idea of displaying a headline (and associative pic if the api provides it), then to the right of that displaying captured keywords, then finally to the right of that displaying the output of a YouTube search. Perhaps we could each research one of those APIs via documentation, practice an API call via postman, and then work together to create an application that chains request objects and build results into DOM elements.

**Comment by njsfield** [comment]
Just saw your comment to Lucy good idea! Incorporating the pirate speak API into the chain would be awesome

**Comment by marisid** [comment]
Nice ideas everyone! Actually, I had a similar idea with Tom, as briefly discussed this evening, to fetch data from Guardian and/or Twitter and show the most popular headlines/ trending posts in a fancy way (whether this involves pirate speak for the titles, getting a relevant image from Flickr etc). Displaying a video from Youtube I think would be tricky, just because it may be more difficult to get a relevant video rather than an image. 

Also, when it comes to displaying, I think we should keep in mind that we are building a mobile first app, so having too many things displaying (although great idea for desktops) may end up look cluttered on mobile view.

**Comment by njsfield** [comment]
Yeah the video aspect could be tricky, I've not used/seen the YouTube api but I know there are a lot of tuts available online for retrieving video ids via a search and then using video/iframe tags to display them. 

Yeah the mobile first/responsive aspect would be tricky I agree, we should spend abit of time of this morn thinking about the UI after deciding on the functionality of the app. A different design approach could perhaps be a one page scroll with each section displaying API data from the last section, which then scrolls into another etc.
